### ISSUE TITLE
Add a deploy:setup and deploy:cold task

### ISSUE THREAD

**Issue by tvdeyen** [railshoster/railshoster#1]
You should add commands for capistranos `deploy:setup` and `deploy:cold` tasks so hooks for these tasks will be invoked.

Example:

In Alchemy CMS we hook after the `deploy:setup` task to create the shared folders we need for uploads and ferret index. And after `deploy:cold` we seed the database.

Running only `railshoster deploy` would not invoke those hooks.

The solution so far is to run `cap deploy:setup` and `cap deploy:cold` manually.

**Comment by ghost** [comment]
Could you send me your deploy.rb to get a picture of it?

We skipped the deploy:setup step because this step is actually thought to prepare your server for a deployment.
Since any railshoster account has already a capistrano compatible structure we've omitted that step.

We could add them as empty steps. What do you think?

**Comment by tvdeyen** [comment]
Thats exactly what we are doing. Preparing the server for deployment. We need additionally shared folders. 

https://github.com/magiclabs/alchemy_cms/blob/master/lib/alchemy/capistrano.rb#L8

In my pull request I added empty steps ;)

**Comment by ghost** [comment]
Just merged your pull request.

Could you please re-verify an AlchemcyCMS installation just to be sure everything works as expected. Now.
That would be awesome and I can close this issue.

**Comment by tvdeyen** [comment]
Working like charm ^_^

Thanks for merging!

Am 29.01.2012 um 18:57 schrieb Julian Fischer:
